language: node_js

node_js:
  - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=c14c771213cee48c0b3f60fccf63f3919a17243222999394ff3498fd7b851394

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build
  - npm run test-coverage
  - BROWSER=true COVERAGE=true

after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
